---


# Instalação do Docker

- name: "Importando a chave do repositorio do Docker para o Debian ou Ubuntu"
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  apt_key: 
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
  become: true
  tags:
    - docker
    - repo


- name: Importando a chave do repositorio do Docker para o Linux Mint
  when: ansible_distribution == "Linux Mint" and ansible_distribution_release in mint_versions
  apt_key: 
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
  become: true
  tags:
    - docker
    - repo


- name: "Importando a chave do repositorio do Docker para o Linux Mint LMDE"
  when: ansible_distribution == "Linux Mint" and ansible_distribution_release in mint_lmde_versions
  apt_key: 
    url: "https://download.docker.com/linux/debian/gpg"
    state: present
  become: true
  tags:
    - docker
    - repo


- name: Adicionando o Repositorio do Docker
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
    update_cache: yes
  become: true
  tags:
    - docker
    - repo


- name: "Adicionando o Repositorio do Docker para o Linux Mint" 
  when: ansible_distribution == "Linux Mint" and ansible_distribution_release in mint_versions
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ the_mint_ubuntu_versions[ansible_distribution_major_version|string] }} stable"
    state: present
    filename: docker
    update_cache: yes
  become: true
  tags:
    - docker
    - repo


- name: "Adicionando o Repositorio do Docker para o Linux Mint LMDE" 
  when: ansible_distribution == "Linux Mint" and ansible_distribution_release in mint_lmde_versions
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ mint_debian_versions[ansible_distribution_major_version|string] }} stable"
    state: present
    filename: docker
    update_cache: yes
  become: true
  tags:
    - docker
    - repo


# Instalando o Docker

- name: Instalando o Docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  notify:
    - Adicionando usuario ao grupo 'docker'
    - Start Docker
  become: true
  tags:
    - docker



