---


# Instalação das dependências do Docker

- name: "Instalando dependências para o Docker"
  apt:
    name: "{{ docker_debian_deps }}"
    state: present
  notify:
    - Adicionando usuario ao grupo 'docker'
    - Start Docker
  become: true
  tags:
    - docker


# Adicionando o repositório do Docker

- name: "Importando a chave do repositorio do Docker para o Debian ou Ubuntu"
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  apt_key: 
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
  become: true
  tags:
    - docker
    - repo


- name: Importando a chave do repositorio do Docker para o Linux Mint
  when: ansible_distribution == "Linux Mint" and ansible_distribution_release in mint_versions
  apt_key: 
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
  become: true
  tags:
    - docker
    - repo


- name: "Importando a chave do repositorio do Docker para o Linux Mint LMDE"
  when: ansible_distribution == "Linux Mint" and ansible_distribution_release in mint_lmde_versions
  apt_key: 
    url: "https://download.docker.com/linux/debian/gpg"
    state: present
  become: true
  tags:
    - docker
    - repo


- name: Adicionando o Repositorio do Docker
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  become: true
  tags:
    - docker
    - repo


- name: "Adicionando o Repositorio do Docker para o Linux Mint" 
  when: ansible_distribution == "Linux Mint" and ansible_distribution_release in mint_versions
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ the_mint_ubuntu_versions[ansible_distribution_major_version|string] }} stable"
    state: present
    filename: docker
  become: true
  tags:
    - docker
    - repo


- name: "Adicionando o Repositorio do Docker para o Linux Mint LMDE" 
  when: ansible_distribution == "Linux Mint" and ansible_distribution_release in mint_lmde_versions
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ mint_debian_versions[ansible_distribution_major_version|string] }} stable"
    state: present
    filename: docker
  become: true
  tags:
    - docker
    - repo


- name: "Atualizando apt cache"
  apt: 
    update_cache: yes 
    cache_valid_time: 7200
  become: true
  tags:
    - docker
    - repo


# Instalando o Docker

- name: Instalando o Docker
  apt:
    name: "{{ packages }}"
    state: present
  notify:
    - Adicionando usuario ao grupo 'docker'
    - Start Docker
  become: true
  tags:
    - docker



