---


- name: "Incluindo tarefas de instalação do Docker no Fedora versão 30 ou inferior"
  when: ansible_distribution_major_version|int < 31
  include_tasks: "fedora/fedora_30_or_less.yml"
  tags: 
   - docker
   - main


- name: "Incluindo tarefas de instalação do Docker no Fedora versão 31"
  when: ansible_distribution_major_version == "31"
  include_tasks: "fedora/fedora_31.yml"
  tags: 
   - docker
   - main


- name: "Incluindo tarefas de instalação do Docker no Fedora versão 32 ou superior"
  when: ansible_distribution_major_version|int > 31
  include_tasks: "fedora/fedora_32_or_higher.yml"
  tags: 
   - docker
   - main