---

# Instalando as dependencias do docker

- name: "Instalando pacote dnf-plugins-core"
  dnf:
    name: dnf-plugins-core
    state: present
    disable_gpg_check: yes
  become: true
  tags:
    - deps
    - docker

# Adicionando o repositório do Docker

- name: "Adicionando repositório do Docker"
  get_url:
    url: "https://download.docker.com/linux/fedora/docker-ce.repo"
    dest: /etc/yum.repos.d/docker-ce.repo
  become: true
  tags:
    - docker
    - repo

# Instalando o Docker

- name: Instalando o Docker
  dnf:
    name: docker-ce
    state: present
  notify:
    - Adicionando usuario ao grupo 'docker'
    - Start Docker
  become: true
  tags:
    - docker
