---

# Instalando as dependencias do docker

- name: "Instalando pacote dnf-plugins-core"
  dnf:
    name: "dnf-plugins-core"
    state: present
    disable_gpg_check: yes
  become: true
  tags:
    - deps
    - docker


- name: "Removendo os pacotes e repositorios docker-ce"
  dnf:
    name: "docker-ce"
    disablerepo: "docker-ce"
    state: absent
    disable_gpg_check: yes
  become: true
  tags:
    - deps
    - docker


- name: 'Executando o comando grub2-mkconfig > sudo grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"'
  shell: 'grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"'
  become: true
  tags:
    - docker
    - docker-fix


- name: 'Executando o comando grub2-mkconfig > sudo firewall-cmd --permanent --zone=trusted --add-interface=docker0'
  shell: 'firewall-cmd --permanent --zone=trusted --add-interface=docker0'
  become: true
  tags:
    - docker
    - docker-fix


- name: 'Executando o comando grub2-mkconfig > sudo firewall-cmd --permanent --zone=FedoraWorkstation --add-masquerade'
  shell: 'firewall-cmd --permanent --zone=FedoraWorkstation --add-masquerade'
  become: true
  tags:
    - docker
    - docker-fix


- name: "Instalando o pacote moby-engine"
  dnf:
    name: "moby-engine"
    state: present
  notify:
    - Adicionando usuario ao grupo 'docker'
    - Start Docker
  become: true
  tags:
    - docker