---

- name: Adicionando usuario ao grupo 'docker'
  user:
    name: "{{ ansible_user_id }}"
    uid: "{{ ansible_user_uid }}"
    group: docker
  become: true

- name: Start Docker
  systemd:
    name: docker
    state: started
    enabled: yes
  become: true